#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Jun 11 10:24:53 MSK 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
