#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sun Aug 30 12:26:36 MSK 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
