#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri May 29 10:47:09 MSK 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
